### PR TITLE
ParadiseSS13 Support

### PR DESCRIPTION
**Pull request by AffectedArc07**
Adds support for ParadiseSS13-style ban DB schema.

I believe the exporter works, but I cant verify because when trying to add it to the CC server, it fails.

```
[20:35:00 INF] (CentCom.Server.BanSources.StandardBanParser) Beginning ban parsing
[20:35:00 INF] (CentCom.Server.BanSources.StandardBanParser) Fetching all bans for Paradise Station...
[20:35:00 ERR] (CentCom.Server.BanSources.StandardBanParser) Failed to get ban data from source, encountered exception during fetch
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at CentCom.Server.Services.StandardProviderService.GetBansAsync(Nullable`1 cursor) in C:\Users\AffectedArc07\Documents\GitHub\CentCom\CentCom.Server\Services\StandardProviderService.cs:line 42
   at CentCom.Server.Services.StandardProviderService.GetBansBatchedAsync(Nullable`1 cursor, IEnumerable`1 searchFor) in C:\Users\AffectedArc07\Documents\GitHub\CentCom\CentCom.Server\Services\StandardProviderService.cs:line 73
   at CentCom.Server.BanSources.StandardBanParser.FetchAllBansAsync() in C:\Users\AffectedArc07\Documents\GitHub\CentCom\CentCom.Server\BanSources\StandardBanParser.cs:line 75
   at CentCom.Server.BanSources.BanParser.ParseBans(IJobExecutionContext context) in C:\Users\AffectedArc07\Documents\GitHub\CentCom\CentCom.Server\BanSources\BanParser.cs:line 149
```

Config used:
```json
    {
      "id": "paradisess13",
      "display": "Paradise Station",
      "roleplayLevel": "Medium",
      "url": "http://localhost:6658/"
    }
```

As such, this PR is on hold until then. I also need to add support for ID exclusions in their own file but that can wait.

---

# Also yes I know my code style edited some other files, ill fix it after.

### CODE REVIEW

**Comment by bobbah** [comment]
The exception that you're getting is because ``response.Data`` ([seen here](https://github.com/AffectedArc07/CentCom/blob/para-stuff/CentCom.Server/Services/StandardProviderService.cs#L42)) is null; can you set a breakpoint and see why your ban service is returning a null response?

**Comment by S34NW** [comment]
Any progress on this?

**Comment by AffectedArc07** [comment]
> Any progress on this?

We were discussing things on discord about it and debugging through, but after a bit we got bored and need to come back to it at some point.

**Comment by bobbah** [comment]
tested in dev, seems fine with the recent patch

**Pull request merged**
